# -*- encoding : utf-8 -*-
autoload :Enumeration,      Rails.root.join('lib/enumerations/enumeration')
autoload :AboutCategory,    Rails.root.join('lib/enumerations/about_category')
autoload :InfoType,         Rails.root.join('lib/enumerations/info_type')
autoload :Language,         Rails.root.join('lib/enumerations/language')
autoload :LanguageLevel,    Rails.root.join('lib/enumerations/language_level')
autoload :OrganizationType, Rails.root.join('lib/enumerations/organization_type')
autoload :StatementAction,  Rails.root.join('lib/enumerations/statement_action')
autoload :StatementState,   Rails.root.join('lib/enumerations/statement_state')
autoload :TagContext,       Rails.root.join('lib/enumerations/tag_context')